// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg-NGrdxAwbqEL7NUMD2iTIcqszTCdG6k',
    appId: '1:850526267429:web:985763533134a370e7f7cc',
    messagingSenderId: '850526267429',
    projectId: 'recordkeeping-e58a2',
    authDomain: 'recordkeeping-e58a2.firebaseapp.com',
    storageBucket: 'recordkeeping-e58a2.appspot.com',
    measurementId: 'G-6RWBLRVLCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcsGrULOQH18CjF6ru0pqNZhtcbBOVnZo',
    appId: '1:850526267429:android:e56791bc4f766c16e7f7cc',
    messagingSenderId: '850526267429',
    projectId: 'recordkeeping-e58a2',
    storageBucket: 'recordkeeping-e58a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKoWBhISNVYviO6RgNxkZS-cppVWn-VAg',
    appId: '1:850526267429:ios:79993f28174724b1e7f7cc',
    messagingSenderId: '850526267429',
    projectId: 'recordkeeping-e58a2',
    storageBucket: 'recordkeeping-e58a2.appspot.com',
    iosClientId: '850526267429-fjbnrgpgcdjpfbs0obmo50h2bef8gkni.apps.googleusercontent.com',
    iosBundleId: 'com.example.recordkeeping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKoWBhISNVYviO6RgNxkZS-cppVWn-VAg',
    appId: '1:850526267429:ios:79993f28174724b1e7f7cc',
    messagingSenderId: '850526267429',
    projectId: 'recordkeeping-e58a2',
    storageBucket: 'recordkeeping-e58a2.appspot.com',
    iosClientId: '850526267429-fjbnrgpgcdjpfbs0obmo50h2bef8gkni.apps.googleusercontent.com',
    iosBundleId: 'com.example.recordkeeping',
  );
}
